import { useState, useEffect } from 'react'
import { useParams, Link } from 'react-router-dom'
import Controls from '../components/Controls.jsx'
import Hero from '../components/Hero.jsx'
import StatsBar from '../components/StatsBar.jsx'
import CountryInfo from '../components/CountryInfo.jsx'
import WCHistory from '../components/WCHistory.jsx'
import Squad from '../components/Squad.jsx'
import Legends from '../components/Legends.jsx'
import Rivalries from '../components/Rivalries.jsx'
import FunFacts from '../components/FunFacts.jsx'
import T from '../components/T.jsx'
import styles from './TeamPage.module.css'

export default function TeamPage() {
  const { slug } = useParams()
  const [data, setData] = useState(null)
  const [error, setError] = useState(false)

  useEffect(() => {
    fetch(`/world-cup-soccer/data/teams/${slug}.json`)
      .then(r => {
        if (!r.ok) throw new Error('not found')
        return r.json()
      })
      .then(setData)
      .catch(() => setError(true))
  }, [slug])

  // Apply team colors as CSS variables on mount/change
  useEffect(() => {
    if (!data) return
    const { primary, secondary, accent } = data.team.colors || {}
    const root = document.documentElement
    if (primary) root.style.setProperty('--color-primary', primary)
    if (secondary) root.style.setProperty('--color-secondary', secondary)
    if (accent) root.style.setProperty('--color-accent', accent)

    return () => {
      root.style.removeProperty('--color-primary')
      root.style.removeProperty('--color-secondary')
      root.style.removeProperty('--color-accent')
    }
  }, [data])

  if (error) {
    return (
      <div className={styles.errorPage}>
        <Controls />
        <div className={styles.errorBox}>
          <div className={styles.errorIcon}>⚽</div>
          <h1><T zh="球队未找到" en="Team Not Found" /></h1>
          <p><T zh={`找不到 "${slug}" 的数据`} en={`No data found for "${slug}"`} /></p>
          <Link to="/" className={styles.backLink}>
            ← <T zh="返回首页" en="Back to Home" />
          </Link>
        </div>
      </div>
    )
  }

  if (!data) {
    return (
      <div className={styles.loadingPage}>
        <Controls />
        <div className={styles.loadingSpinner}>⚽</div>
      </div>
    )
  }

  return (
    <div className={styles.page}>
      <Controls />

      <Link to="/" className={styles.backBtn}>
        ← <T zh="所有球队" en="All Teams" />
      </Link>

      <Hero team={data.team} worldCup={data.world_cup} />
      <StatsBar worldCup={data.world_cup} team={data.team} />
      <CountryInfo country={data.country} />
      <WCHistory worldCup={data.world_cup} />
      <Squad squad={data.squad_2026} />
      <Legends legends={data.legends} />
      <Rivalries rivalries={data.rivalries} />
      <FunFacts facts={data.fun_facts} />

      <footer className={styles.footer}>
        <T
          zh={`${data.team.name_zh} · 由 Claude Code 生成 · 数据截至 ${data.meta?.generated || ''}`}
          en={`${data.team.name_en} · AI-generated by Claude Code · Data as of ${data.meta?.generated || ''}`}
        />
      </footer>
    </div>
  )
}
